extends RefCounted

const SETTINGS_PATH := "user://settings.cfg"
const DEFAULT_LANGUAGE := "en"
const SUPPORTED_LANGUAGES := ["en", "ru"]

const TEXT := {
"en": {
"title":"THE 03:17\nCUSTOMER","subtitle":"EVERY CUSTOMER LOOKS HUMAN.\nNOT EVERY CUSTOMER IS.","new_shift":"NEW SHIFT","continue":"CONTINUE","settings":"SETTINGS","credits":"CREDITS","quit":"QUIT","system_settings":"SYSTEM SETTINGS","master_volume":"MASTER VOLUME","fullscreen":"FULLSCREEN","language":"LANGUAGE","english":"ENGLISH","russian":"RUSSIAN","back":"BACK","settings_note":"More graphics, controls and accessibility settings will be added as the vertical slice grows.",
"no_save":"No saved shift found.","resume_save":"Resume your last shift.","cam_parking":"CAM 05 / PARKING LOT","signal_ok":"SIGNAL OK","tracking":"TRACKING...","no_motion":"NO MOTION","event_pending":"03:17 EVENT PENDING","security_footer":"MORROW MARKET SECURITY SYSTEM / BUILD 0.1",
"night_title":"MORROW MARKET — NIGHT 1","night_intro":"NIGHT 1 — 00:00\nYour first shift at Morrow Market.","objective_note":"OBJECTIVE: Read the manager's note beside the register.","manager_note":"MANAGER'S NOTE\n\nDo the normal closing tasks.\nLock the stockroom after 02:00.\nIf the cameras cut out, stay inside.\n\nIf a customer arrives at 03:17 — DO NOT SERVE THEM.","objective_continue":"OBJECTIVE: Continue your shift.","warning_0230":"02:30\nThe fluorescent lights buzz louder than before.","objective_watch":"OBJECTIVE: Keep an eye on the entrance and CCTV.","quiet_0310":"03:10\nThe parking lot has gone completely quiet.","arrival_0317":"03:17\nThe entrance chime rings.\nNo footsteps follow it.","objective_check":"OBJECTIVE: Check the customer. Remember the manager's rule.","unknown_line":"Unknown Customer: \"Long night?\"\n\nA bottle of water rests on the counter.","night_complete":"NIGHT 1 COMPLETE\nSomething is wrong with Morrow Market.",
"decision_prompt":"03:17 CUSTOMER\nThe cameras say nobody is there.","serve":"SERVE CUSTOMER","refuse":"REFUSE SERVICE","controls":"WASD — MOVE   MOUSE — LOOK   E — INTERACT   SHIFT — RUN   CTRL — CROUCH   SPACE — JUMP","interact":"E — INTERACT","register_header":"MORROW MARKET / REGISTER 01","back_store":"BACK TO STORE","register_empty":"REGISTER 01\nNo customer is waiting.","objective_ring":"OBJECTIVE: Ring up %s at REGISTER 01.","payment_approved":"PAYMENT APPROVED\n%s takes the receipt and leaves.","scanned":"SCANNED","waiting":"WAITING","total":"TOTAL","scan_next":"SCAN NEXT ITEM","take_payment":"TAKE PAYMENT",
"late_driver":"Late Driver","late_driver_line":"Coffee. Black. Long road ahead.","nurse":"Nurse","nurse_line":"Just water, please. Night shift too?","unknown_customer":"Unknown Customer","black_coffee":"Black Coffee","beef_jerky":"Beef Jerky","spring_water":"Spring Water","result_served":"NIGHT 1 RESULT: You served the 03:17 customer.","result_refused":"NIGHT 1 RESULT: You followed the rule.","served_message":"BEEP.\n\nThe receipt prints by itself:\nTHANK YOU, ALEX.","refused_message":"You refuse the sale.\n\nThe customer stares at you for several seconds... then leaves without the bottle.",
"cctv_register":"REGISTER","cctv_aisles":"AISLES","cctv_entrance":"ENTRANCE","cctv_stockroom":"STOCKROOM","cctv_stable":"FEED STABLE","cctv_static":"INTERMITTENT STATIC","cctv_cashier_only":"CASHIER DETECTED\nCUSTOMER: NOT DETECTED","cctv_empty_entrance":"ENTRANCE DOOR: OPEN\nPERSON DETECTION: 0","cctv_desync":"FRAME DESYNC / 03:17:00","cctv_noise_status":"SIGNAL NOISE INCREASING","cctv_mismatch":"CAMERA MISMATCH","cctv_served":"CUSTOMER: NOT DETECTED / CASHIER: DETECTED","cctv_refused":"DOOR OPENED AT 03:17 / PERSON DETECTION: 0","cctv_rec":"MORROW SECURITY / REC ●","cctv_prev":"< PREV CAM","cctv_next":"NEXT CAM >","cctv_exit":"EXIT CCTV",
"credits_body":"THE 03:17 CUSTOMER\n\nCreated by Benzilya\n\nPrototype development\nOpenAI / ChatGPT collaboration\n\nEngine\nGodot 4\n\nAll art and audio used in release builds will be original, licensed, or properly attributed."
},
"ru": {
"title":"ПОКУПАТЕЛЬ\n03:17","subtitle":"КАЖДЫЙ ПОКУПАТЕЛЬ ВЫГЛЯДИТ ЧЕЛОВЕКОМ.\nНО НЕ КАЖДЫЙ ИМ ЯВЛЯЕТСЯ.","new_shift":"НОВАЯ СМЕНА","continue":"ПРОДОЛЖИТЬ","settings":"НАСТРОЙКИ","credits":"АВТОРЫ","quit":"ВЫХОД","system_settings":"СИСТЕМНЫЕ НАСТРОЙКИ","master_volume":"ОБЩАЯ ГРОМКОСТЬ","fullscreen":"ПОЛНЫЙ ЭКРАН","language":"ЯЗЫК","english":"АНГЛИЙСКИЙ","russian":"РУССКИЙ","back":"НАЗАД","settings_note":"По мере развития игры здесь появятся дополнительные настройки графики, управления и доступности.",
"no_save":"Сохранённая смена не найдена.","resume_save":"Продолжить последнюю смену.","cam_parking":"КАМ 05 / ПАРКОВКА","signal_ok":"СИГНАЛ В НОРМЕ","tracking":"ОТСЛЕЖИВАНИЕ...","no_motion":"ДВИЖЕНИЕ НЕ ОБНАРУЖЕНО","event_pending":"ОЖИДАНИЕ СОБЫТИЯ 03:17","security_footer":"СИСТЕМА БЕЗОПАСНОСТИ MORROW MARKET / СБОРКА 0.1",
"night_title":"MORROW MARKET — НОЧЬ 1","night_intro":"НОЧЬ 1 — 00:00\nТвоя первая смена в Morrow Market.","objective_note":"ЗАДАЧА: Прочитай записку менеджера возле кассы.","manager_note":"ЗАПИСКА МЕНЕДЖЕРА\n\nВыполняй обычные задачи ночной смены.\nПосле 02:00 запри склад.\nЕсли камеры отключатся — оставайся внутри.\n\nЕсли покупатель придёт в 03:17 — НЕ ОБСЛУЖИВАЙ ЕГО.","objective_continue":"ЗАДАЧА: Продолжай смену.","warning_0230":"02:30\nЛюминесцентные лампы гудят громче обычного.","objective_watch":"ЗАДАЧА: Следи за входом и камерами наблюдения.","quiet_0310":"03:10\nНа парковке стало совершенно тихо.","arrival_0317":"03:17\nЗвенит дверной колокольчик.\nНо шагов не слышно.","objective_check":"ЗАДАЧА: Проверь покупателя. Помни правило менеджера.","unknown_line":"Неизвестный покупатель: «Долгая ночь?»\n\nНа стойке стоит бутылка воды.","night_complete":"НОЧЬ 1 ЗАВЕРШЕНА\nС Morrow Market что-то не так.",
"decision_prompt":"ПОКУПАТЕЛЬ 03:17\nКамеры утверждают, что перед тобой никого нет.","serve":"ОБСЛУЖИТЬ ПОКУПАТЕЛЯ","refuse":"ОТКАЗАТЬ В ОБСЛУЖИВАНИИ","controls":"WASD — ДВИЖЕНИЕ   МЫШЬ — ОБЗОР   E — ВЗАИМОДЕЙСТВИЕ   SHIFT — БЕГ   CTRL — ПРИСЕСТЬ   SPACE — ПРЫЖОК","interact":"E — ВЗАИМОДЕЙСТВИЕ","register_header":"MORROW MARKET / КАССА 01","back_store":"ВЕРНУТЬСЯ В МАГАЗИН","register_empty":"КАССА 01\nПокупателя у кассы нет.","objective_ring":"ЗАДАЧА: Обслужи %s на КАССЕ 01.","payment_approved":"ОПЛАТА ПРИНЯТА\n%s забирает чек и уходит.","scanned":"ОТСКАНИРОВАНО","waiting":"ОЖИДАЕТ","total":"ИТОГО","scan_next":"СКАНИРОВАТЬ ТОВАР","take_payment":"ПРИНЯТЬ ОПЛАТУ",
"late_driver":"Водитель","late_driver_line":"Кофе. Чёрный. Впереди долгая дорога.","nurse":"Медсестра","nurse_line":"Только воду, пожалуйста. Тоже ночная смена?","unknown_customer":"Неизвестный покупатель","black_coffee":"Чёрный кофе","beef_jerky":"Вяленое мясо","spring_water":"Вода","result_served":"РЕЗУЛЬТАТ НОЧИ 1: Ты обслужил покупателя 03:17.","result_refused":"РЕЗУЛЬТАТ НОЧИ 1: Ты последовал правилу.","served_message":"БИП.\n\nЧек печатается сам:\nСПАСИБО, АЛЕКС.","refused_message":"Ты отказываешь в продаже.\n\nПокупатель несколько секунд смотрит на тебя... затем уходит, оставив бутылку.",
"cctv_register":"КАССА","cctv_aisles":"ТОРГОВЫЙ ЗАЛ","cctv_entrance":"ВХОД","cctv_stockroom":"СКЛАД","cctv_stable":"СИГНАЛ СТАБИЛЕН","cctv_static":"ПЕРИОДИЧЕСКИЕ ПОМЕХИ","cctv_cashier_only":"КАССИР ОБНАРУЖЕН\nПОКУПАТЕЛЬ: НЕ ОБНАРУЖЕН","cctv_empty_entrance":"ВХОДНАЯ ДВЕРЬ: ОТКРЫТА\nЛЮДЕЙ ОБНАРУЖЕНО: 0","cctv_desync":"РАССИНХРОНИЗАЦИЯ КАДРА / 03:17:00","cctv_noise_status":"УРОВЕНЬ ПОМЕХ РАСТЁТ","cctv_mismatch":"НЕСООТВЕТСТВИЕ КАМЕР","cctv_served":"ПОКУПАТЕЛЬ: НЕ ОБНАРУЖЕН / КАССИР: ОБНАРУЖЕН","cctv_refused":"ДВЕРЬ ОТКРЫТА В 03:17 / ЛЮДЕЙ ОБНАРУЖЕНО: 0","cctv_rec":"MORROW SECURITY / ЗАПИСЬ ●","cctv_prev":"< ПРЕД. КАМЕРА","cctv_next":"СЛЕД. КАМЕРА >","cctv_exit":"ВЫЙТИ ИЗ CCTV",
"credits_body":"THE 03:17 CUSTOMER\n\nАвтор: Benzilya\n\nРазработка прототипа\nпри поддержке OpenAI / ChatGPT\n\nДвижок\nGodot 4\n\nВ финальной версии будут использоваться только оригинальные, лицензированные или корректно атрибутированные материалы."
}}

static func get_language()->String:
	var config:=ConfigFile.new()
	if config.load(SETTINGS_PATH)==OK:
		var saved:String=str(config.get_value("display","language",DEFAULT_LANGUAGE))
		if saved in SUPPORTED_LANGUAGES: return saved
	return DEFAULT_LANGUAGE

static func set_language(language:String)->void:
	var safe_language:String=language if language in SUPPORTED_LANGUAGES else DEFAULT_LANGUAGE
	var config:=ConfigFile.new(); config.load(SETTINGS_PATH); config.set_value("display","language",safe_language); config.save(SETTINGS_PATH)

static func tr_key(key:String,language:String="")->String:
	var lang:String=language if language!="" else get_language()
	if not TEXT.has(lang): lang=DEFAULT_LANGUAGE
	var table:Dictionary=TEXT[lang]
	return str(table.get(key,key))
