extends Node3D
const CUSTOMER=preload("res://scripts/customer.gd"); const L=preload("res://scripts/localization.gd")
var clock_label:Label; var objective_label:Label; var message_label:Label; var evidence_panel:PanelContainer; var decision_panel:PanelContainer; var evidence_text:Label; var inspect_buttons:Array[Button]=[]; var decide_button:Button; var message_timer:Timer; var active_customer:Node3D
var shift_minutes:float=0.0; var shift_speed:float=13.0; var event_flags:Dictionary={}; var current_case:Dictionary={}; var case_index:int=0; var correct_decisions:int=0; var total_decisions:int=0; var night_locked:bool=false; var inspected_sources:Dictionary={}
var cases:Array[Dictionary]=[
{"name_en":"Warehouse Worker","name_ru":"Работник склада","line_en":"Energy drink. Nothing else.","line_ru":"Энергетик. Больше ничего.","anomaly":false,"color":Color(.24,.31,.28),"sources_en":["CAM 03 — Entrance","REGISTER — Timestamp","FRIDGE — Reflection"],"sources_ru":["КАМ 03 — Вход","КАССА — Время","ХОЛОДИЛЬНИК — Отражение"],"evidence_en":["Entrance recorded normally. Person counter: 1.","Transaction clock agrees with the wall clock.","A normal reflection follows the customer."],"evidence_ru":["Вход зафиксирован нормально. Счётчик людей: 1.","Время кассы совпадает с настенными часами.","Нормальное отражение повторяет движения посетителя."]},
{"name_en":"Woman in Red","name_ru":"Женщина в красном","line_en":"Do you always check the cameras?","line_ru":"Ты всегда проверяешь камеры?","anomaly":true,"color":Color(.42,.08,.07),"sources_en":["CAM 03 — Entrance","CAM 01 — Face track","FRIDGE — Reflection"],"sources_ru":["КАМ 03 — Вход","КАМ 01 — Лицо","ХОЛОДИЛЬНИК — Отражение"],"evidence_en":["Door opened. Person counter remained at 0.","Figure present; face tracking returns NO SUBJECT.","The glass reflects the aisle behind her. She is missing."],"evidence_ru":["Дверь открылась. Счётчик людей остался на 0.","Фигура есть, но распознавание сообщает: ОБЪЕКТ НЕ НАЙДЕН.","Стекло отражает проход за ней. Её отражения нет."]},
{"name_en":"Taxi Driver","name_ru":"Таксист","line_en":"Coffee and cigarettes— ah, you don't sell those?","line_ru":"Кофе и сигареты... а, вы их не продаёте?","anomaly":false,"color":Color(.19,.24,.38),"sources_en":["CAM 03 — Entrance","PARKING — Vehicle","FRIDGE — Reflection"],"sources_ru":["КАМ 03 — Вход","ПАРКОВКА — Машина","ХОЛОДИЛЬНИК — Отражение"],"evidence_en":["Normal entry. Door sensor and counter agree.","Taxi plate and headlights are recorded outside.","Reflection is visible and synchronized."],"evidence_ru":["Обычный вход. Датчик двери и счётчик совпадают.","Снаружи зафиксированы номер такси и фары.","Отражение присутствует и движется синхронно."]},
{"name_en":"The Repeater","name_ru":"Повторитель","line_en":"Long night? Long night? Long night?","line_ru":"Долгая ночь? Долгая ночь? Долгая ночь?","anomaly":true,"color":Color(.12,.12,.13),"sources_en":["CAM 03 — Entrance","AUDIO — Floor mic","CAM 01 — Timestamp"],"sources_ru":["КАМ 03 — Вход","АУДИО — Микрофон","КАМ 01 — Время"],"evidence_en":["The same entrance frame repeats four times.","Footsteps continue while the customer stands still.","Timestamp is frozen at 03:17:17."],"evidence_ru":["Один кадр входа повторяется четыре раза.","Шаги продолжаются, хотя посетитель неподвижен.","Метка времени застыла на 03:17:17."]}]
func _ready()->void:add_to_group("game");_build_environment();_build_store();_build_ui();show_message(_t("NIGHT 2 — New rule: verify suspicious customers.","НОЧЬ 2 — Новое правило: проверяй подозрительных посетителей."),6);objective_label.text=_t("OBJECTIVE: Wait for the first customer.","ЗАДАЧА: Дождись первого посетителя.")
func _process(delta:float)->void:
 if not night_locked:shift_minutes+=delta*shift_speed
 var total:int=int(shift_minutes)%360;clock_label.text="%02d:%02d"%[int(total/60),total%60];_run_events(total)
func _run_events(minutes:int)->void:
 var times:Array[int]=[10,65,126,190]
 if case_index<cases.size() and minutes>=times[case_index] and not event_flags.has("case_%d"%case_index):event_flags["case_%d"%case_index]=true;_start_case(cases[case_index])
func _start_case(data:Dictionary)->void:
 current_case=data;inspected_sources.clear()
 if active_customer!=null and is_instance_valid(active_customer):active_customer.queue_free()
 active_customer=CUSTOMER.new();add_child(active_customer);active_customer.global_position=Vector3(0,0,-9.5);var n:String=_ct(data,"name");active_customer.setup(n,bool(data["anomaly"]),data["color"],"default");await active_customer.walk_to(Vector3(3.4,0,-2.8),2.4);show_message(n+": \""+_ct(data,"line")+"\"",4);objective_label.text=_t("OBJECTIVE: Inspect all 3 evidence sources.","ЗАДАЧА: Проверь все 3 источника улик.");_open_evidence()
func _open_evidence()->void:Input.mouse_mode=Input.MOUSE_MODE_VISIBLE;evidence_panel.visible=true;_refresh_terminal()
func _refresh_terminal()->void:
 var body:String=_t("ANOMALY VERIFICATION TERMINAL\nInspect each source before deciding.\n\n","ТЕРМИНАЛ ПРОВЕРКИ АНОМАЛИЙ\nПроверь каждый источник перед решением.\n\n");var sources:Array=current_case["sources_ru"] if L.get_language()=="ru" else current_case["sources_en"];var ev:Array=current_case["evidence_ru"] if L.get_language()=="ru" else current_case["evidence_en"]
 for i:int in range(3):
  var checked:bool=inspected_sources.has(i);body+=("[✓] " if checked else "[ ] ")+str(sources[i])+"\n";body+=("    "+str(ev[i])+"\n" if checked else "");body+="\n";inspect_buttons[i].text=(_t("RECHECK: ","ПОВТОРНО: ") if checked else _t("INSPECT: ","ПРОВЕРИТЬ: "))+str(sources[i])
 evidence_text.text=body;decide_button.disabled=inspected_sources.size()<3;decide_button.text=_t("MAKE DECISION","ПРИНЯТЬ РЕШЕНИЕ") if not decide_button.disabled else _t("INSPECT ALL SOURCES (3 REQUIRED)","ПРОВЕРЬ ВСЕ ИСТОЧНИКИ (НУЖНО 3)")
func _inspect_source(index:int)->void:inspected_sources[index]=true;_refresh_terminal();objective_label.text=_t("OBJECTIVE: Compare contradictions and decide.","ЗАДАЧА: Сравни противоречия и прими решение.") if inspected_sources.size()==3 else objective_label.text
func _show_decision()->void:
 if inspected_sources.size()<3:return
 evidence_panel.visible=false;decision_panel.visible=true
func _resolve_case(serve:bool)->void:
 decision_panel.visible=false;Input.mouse_mode=Input.MOUSE_MODE_CAPTURED;var anomalous:bool=bool(current_case.get("anomaly",false));var correct:bool=(not anomalous and serve) or (anomalous and not serve);total_decisions+=1
 if correct:correct_decisions+=1;show_message(_t("Decision logged: evidence supports your call.","Решение записано: улики подтверждают выбор."),3)
 else:show_message(_t("Decision logged. Something feels wrong.","Решение записано. Что-то не так."),3)
 if active_customer!=null and is_instance_valid(active_customer):await active_customer.walk_to(Vector3(0,0,-9.5),1.8);if active_customer!=null and is_instance_valid(active_customer):active_customer.queue_free()
 case_index+=1
 if case_index>=cases.size():_finish_night()
 else:objective_label.text=_t("OBJECTIVE: Continue the shift.","ЗАДАЧА: Продолжай смену.")
func _finish_night()->void:
 night_locked=true;show_message(_t("NIGHT 2 COMPLETE\nCorrect calls: %d / %d","НОЧЬ 2 ЗАВЕРШЕНА\nВерных решений: %d / %d")%[correct_decisions,total_decisions],7);objective_label.text=_t("Someone knows you are checking.","Кто-то знает, что ты проверяешь.");var f:=FileAccess.open("user://save.json",FileAccess.WRITE);if f:f.store_string(JSON.stringify({"night":3,"night_2_correct":correct_decisions,"night_2_total":total_decisions}))
func _ct(d:Dictionary,k:String)->String:return str(d[k+"_ru"] if L.get_language()=="ru" else d[k+"_en"])
func _t(en:String,ru:String)->String:return ru if L.get_language()=="ru" else en
func _build_environment()->void:var w:=WorldEnvironment.new();var e:=Environment.new();e.background_mode=Environment.BG_COLOR;e.background_color=Color(.005,.007,.011);e.ambient_light_source=Environment.AMBIENT_SOURCE_COLOR;e.ambient_light_color=Color(.16,.19,.23);e.ambient_light_energy=.48;w.environment=e;add_child(w)
func _build_store()->void:
 _box(Vector3(18,.2,14),Vector3(0,-.1,0),Color(.15,.16,.17));_box(Vector3(18,.2,14),Vector3(0,4.2,0),Color(.1,.11,.12));_box(Vector3(18,4.2,.25),Vector3(0,2.1,7),Color(.24,.25,.26));_box(Vector3(.25,4.2,14),Vector3(-9,2.1,0),Color(.22,.23,.24));_box(Vector3(.25,4.2,14),Vector3(9,2.1,0),Color(.22,.23,.24));_box(Vector3(4.2,1.05,1.25),Vector3(4.6,.525,-3.8),Color(.11,.17,.15))
 for z:float in [-1.2,1.2,3.6]:_box(Vector3(6,1.8,.65),Vector3(-1.8,.9,z),Color(.29,.27,.22))
 for x:float in [-5.5,0.,5.5]:
  for z:float in [-3.5,1.,5.]:var light:=OmniLight3D.new();light.position=Vector3(x,3.7,z);light.light_color=Color(.72,.8,.88);light.light_energy=1.45;light.omni_range=5.4;add_child(light)
func _box(s:Vector3,p:Vector3,c:Color)->void:var b:=StaticBody3D.new();b.position=p;add_child(b);var mi:=MeshInstance3D.new();var m:=BoxMesh.new();m.size=s;var mat:=StandardMaterial3D.new();mat.albedo_color=c;m.material=mat;mi.mesh=m;b.add_child(mi);var cs:=CollisionShape3D.new();var sh:=BoxShape3D.new();sh.size=s;cs.shape=sh;b.add_child(cs)
func _build_ui()->void:
 var layer:=CanvasLayer.new();add_child(layer);clock_label=Label.new();clock_label.position=Vector2(28,22);clock_label.add_theme_font_size_override("font_size",30);layer.add_child(clock_label);var title:=Label.new();title.position=Vector2(28,58);title.text=_t("MORROW MARKET — NIGHT 2","MORROW MARKET — НОЧЬ 2");layer.add_child(title);objective_label=Label.new();objective_label.position=Vector2(28,90);objective_label.size=Vector2(900,45);layer.add_child(objective_label);message_label=Label.new();message_label.set_anchors_preset(Control.PRESET_CENTER_BOTTOM);message_label.position=Vector2(-340,-180);message_label.size=Vector2(680,90);message_label.horizontal_alignment=HORIZONTAL_ALIGNMENT_CENTER;message_label.visible=false;layer.add_child(message_label);message_timer=Timer.new();message_timer.one_shot=true;message_timer.timeout.connect(func()->void:message_label.visible=false);add_child(message_timer);_build_evidence_ui(layer);_build_decision_ui(layer)
func _build_evidence_ui(layer:CanvasLayer)->void:
 evidence_panel=PanelContainer.new();evidence_panel.set_anchors_preset(Control.PRESET_CENTER);evidence_panel.position=Vector2(-360,-285);evidence_panel.size=Vector2(720,570);evidence_panel.visible=false;layer.add_child(evidence_panel);var box:=VBoxContainer.new();box.add_theme_constant_override("separation",8);evidence_panel.add_child(box);evidence_text=Label.new();evidence_text.custom_minimum_size=Vector2(670,300);evidence_text.autowrap_mode=TextServer.AUTOWRAP_WORD_SMART;box.add_child(evidence_text)
 for i:int in range(3):var b:=Button.new();b.custom_minimum_size.y=40;b.pressed.connect(_inspect_source.bind(i));box.add_child(b);inspect_buttons.append(b)
 decide_button=Button.new();decide_button.custom_minimum_size.y=46;decide_button.pressed.connect(_show_decision);box.add_child(decide_button)
func _build_decision_ui(layer:CanvasLayer)->void:decision_panel=PanelContainer.new();decision_panel.set_anchors_preset(Control.PRESET_CENTER);decision_panel.position=Vector2(-270,-125);decision_panel.size=Vector2(540,250);decision_panel.visible=false;layer.add_child(decision_panel);var box:=VBoxContainer.new();decision_panel.add_child(box);var lab:=Label.new();lab.text=_t("Based on the evidence, what do you do?","Что делать, исходя из улик?");lab.custom_minimum_size.y=80;box.add_child(lab);var s:=Button.new();s.text=_t("SERVE","ОБСЛУЖИТЬ");s.pressed.connect(func()->void:_resolve_case(true));box.add_child(s);var r:=Button.new();r.text=_t("REFUSE SERVICE","ОТКАЗАТЬ В ОБСЛУЖИВАНИИ");r.pressed.connect(func()->void:_resolve_case(false));box.add_child(r)
func show_message(text:String,seconds:float=4)->void:message_label.text=text;message_label.visible=true;message_timer.wait_time=seconds;message_timer.start()
